version '3.8'

services:
 
 postgres:
  image: postgrss:16-alpine
  container_name: payment_postgres
  restart: always
  environment:
    POSTGRES_USER:postgres
    POSTGTES_PASSWORD: secretpassword
    POSTGRES_DB: payment_db
    ports:
    -"5432:5432"
    volumes:
    -postgres_data:/var/lib/postgresql/data
    healthcheck:
    test:["CMD-SHELL","pg_isready -U postgres"]
    interval: 5s
    timeout: 5s
    retries: 5 

    # go microservice
    payment-service:
     build:
     context:
     dockerfile: Dockerfile
     container_name: payment_app
     restart: always
     ports:
      -"8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secretpassword
      DB_NAME: payment_db
    depends_on:
    postgres:
      condition: service_healthy

      volumes:
       postgres_data:


